### ISSUE TITLE
ConstraintViolationError: Exceed password retry limit. Account locked.

### ISSUE THREAD

**Issue by jjg77** [vesse/passport-ldapauth#21]
Using passport-ldapauth module and getting this error when trying to login using a locked account. The trace below points to ldapjs client. Any ideas?

```
ConstraintViolationError: Exceed password retry limit. Account locked.
at messageCallback (C:\Users\jg63717\projects\raap\node_modules\passport-ldapauth\node_modules\ldapauth-fork\node_modules\ldapjs\lib\client\client.js:867:40)
at Parser.onMessage (C:\Users\jg63717\projects\raap\node_modules\passport-ldapauth\node_modules\ldapauth-fork\node_modules\ldapjs\lib\client\client.js:199:12)
at Parser.emit (events.js:95:17)
at Parser.write (C:\Users\jg63717\projects\raap\node_modules\passport-ldapauth\node_modules\ldapauth-fork\node_modules\ldapjs\lib\messages\parser.js:105:8)
at CleartextStream.onData (C:\Users\jg63717\projects\raap\node_modules\passport-ldapauth\node_modules\ldapauth-fork\node_modules\ldapjs\lib\client\client.js:155:24)
at CleartextStream.emit (events.js:95:17)
at CleartextStream. (stream_readable.js:764:14)
at CleartextStream.emit (events.js:92:17)
at emitReadable (_stream_readable.js:426:10)
at _stream_readable.js:419:7
```

**Comment by vesse** [comment]
Could you try adding `ConstraintViolationError` to error handler in your `passport-ldapauth` installation so it would be handled like `InvalidCredentialsError`? 

I would expect that to happen so that the error is returned to `passport-ldapauth`, but since it currently does not treat that particular error as a login failure but execption ([see here](https://github.com/vesse/passport-ldapauth/blob/ac6e5757bb0d950fb5f65488f6ebbab5420a1579/lib/passport-ldapauth/strategy.js#L143-L145)) it will raise an error.

**Comment by jjg77** [comment]
Fixed it and submitted pull request.
