### ISSUE TITLE
DTraceProviderBindings dtract-provider errors

### ISSUE THREAD

**Issue by mikedevita** [vesse/passport-ldapauth#62]
## Problem Description
Using [balderdashy/sails@0.11.x](https://github.com/balderdashy/sails) with passport-ldapauth when the app starts it throws a bunch of dtrace-provider related errors.

```
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mhdevita/Web Development/sapinfrastructure/backend/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/mhdevita/Web Development/sapinfrastructure/backend/node_modules/ldapauth-fork/node_modules/ldapjs/lib/dtrace.js:84:20
    at Object.<anonymous> (/Users/mhdevita/Web Development/sapinfrastructure/backend/node_modules/ldapauth-fork/node_modules/ldapjs/lib/dtrace.js:124:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10) code: 'MODULE_NOT_FOUND' }
```

I have attempted adding the `"ldapjs": "mcavage/node-ldapjs",` into my `package.json` as described in issue #27 but this did not resolve the errors.

## Steps to Reproduce
1. Install sailsjs@0.11x
1. Install passport, passport-ldapauth
1. start the app via `node app.js` 
1. errors as mentioned above show up

## System Information
**Node Version:** 6.10.1
**OS Version:** OS X SIerra (10.12)
**NPM Version:** 3.10.10
**Yarn Version:** 0.21.3

**Comment by mikedevita** [comment]
looks like my issue was i didn't have xcode fully installed. I determined this by running `V="true" npm i dtrace-provider` which gave me errors relating to gcc, and then google led me to [this](http://railsapps.github.io/xcode-command-line-tools.html) guide which after installing the xcode-cli tools my issue was resolved.

I had to then run `rm -rf node_modules` and then reinstall all my modules via `yarn` command. Now the errors are gone.
