### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by Funnybanny** [vesse/passport-ldapauth#66]
Here is how i set it up : 
```
let OPT = {
        server: {
            url: 'ldap://****:389',
            bindDN: "",
            bindCredentials: "",
            searchBase: 'ou=Users,dc=astron,dc=hu',
            searchFilter: "(uid={{username}})"
        },
        usernameField: 'username',
        passwordField: 'password',
    };
passport.use(new LdapStrategy(OPT, function (user, done) {
        if (user != null){
            return done(null, user);
        }
        else return done(new Error("i dont know"), null)
    }))

```
and this is where is use it: 
```
async authenticate(req, res): Promise<boolean> {
        return new Promise<boolean>((resolve,
            reject) => {
            let authenticate: express.RequestHandler = <express.RequestHandler>passport.authenticate('ldapauth', (error, user, info) => {
                if (error) {
                    return reject(error);
                }
                if (!user) {
                    return resolve(false);
                }
                req.user = user;
                resolve(true);
            });
            authenticate(req, res,
                null);
        }
        )
    }
```
and i get this error: 

> Error: getaddrinfo ENOTFOUND **** ****:389
>     at errnoException (dns.js:28:10)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Update: I am sure the username password and the url is correct

**Comment by vesse** [comment]
This is an error coming from Node when it cannot resolve the domain name. Since the format of the `url` seems correct it could be caused by just your env not being able to resolve the name. Anyways, this is unlikely an issue in this library as this just uses [ldapjs](https://www.npmjs.com/package/ldapjs)
