### ISSUE TITLE
Error: Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by kareha** [vesse/passport-ldapauth#67]
Hi,

I'm getting Errors when using passport-ldapauth.

Here is one of them:
```
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/..../node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /Users/..../node_modules/ldapjs/lib/dtrace.js:84:20
    at Object.<anonymous> (/Users/..../node_modules/ldapjs/lib/dtrace.js:124:2)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10) code: 'MODULE_NOT_FOUND' }
```

Can you fix this?
Thank you

**Comment by kareha** [comment]
I found something:

https://github.com/vesse/passport-ldapauth/issues/62#issuecomment-290469351
