### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by williehallock802** [vesse/passport-ldapauth#93]
This may not be your issue, but if you are not aware of it, it may be important.

I created a new directory, did a simple "npm init" and then "npm install --save passport-ldapauth" and saw the errors below in the output.

I am not sure if they will have any impact on how the package operates.

```
> dtrace-provider@0.8.8 install /private/tmp/npm_test/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 794, in Write
    extra_mac_bundle_resources, part_of_all)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 900, in WriteActions
    env = self.GetSortedXcodeEnv()
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1885, in GetSortedXcodeEnv
    additional_settings)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1616, in GetSortedXcodeEnv
    additional_settings)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/13.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/npm_test/node_modules/dtrace-provider
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN npm_test@1.0.0 No description
npm WARN npm_test@1.0.0 No repository field.

+ passport-ldapauth@2.1.3
added 49 packages from 167 contributors and audited 67 packages in 2.44s
found 0 vulnerabilities
```

**Comment by vesse** [comment]
Yeah dtrace-provider causes installation errors [every now and then](https://github.com/vesse/passport-ldapauth/issues?q=dtrace-provider) but nothing to worry about, it is [an optional dependency of ldapjs](https://github.com/ldapjs/node-ldapjs/blob/a4bdcbb7644be3f61b5c5ef8bcf26c105e6af5b5/package.json#L42-L44)
